package conf

const (
	OPT_TYPE_CONNECTION = iota
	OPT_TYPE_CLOSE_CONNECTION
	OPT_TYPE_START_PROXY
	OPT_TYPE_STOP_PROXY
	OPT_TYPE_PROXY_LIST
	OPT_TYPE_START_VNC
	OPT_TYPE_STOP_VNC
	OPT_TYPE_SET_CONFIG
)

var (
	FLAG_UNKNOWN   = 0
	FLAG_CANDIDATE = 1
	FLAG_ANWER     = 2
	FLAG_OFFER     = 3

	//Connection pair types
	CP_TYPE_CLIENT = "_client"
	CP_TYPE_SERVER = "_server"
)

const (
	CONNECTION_TYPE_SSH = iota
	CONNECTION_TYPE_VNC
)
